package com.afeiluo.cook.dao;

import com.afeiluo.cook.entity.DishStep;
import com.afeiluo.cook.entity.DishStepCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DishStepMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_step
     *
     * @mbggenerated
     */
    int countByExample(DishStepCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_step
     *
     * @mbggenerated
     */
    int deleteByExample(DishStepCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_step
     *
     * @mbggenerated
     */
    int insert(DishStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_step
     *
     * @mbggenerated
     */
    int insertSelective(DishStep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_step
     *
     * @mbggenerated
     */
    List<DishStep> selectByExample(DishStepCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_step
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DishStep record, @Param("example") DishStepCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_step
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DishStep record, @Param("example") DishStepCriteria example);
}