package com.afeiluo.cook.dao;

import com.afeiluo.cook.entity.DishComment;
import com.afeiluo.cook.entity.DishCommentCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DishCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_comment
     *
     * @mbggenerated
     */
    int countByExample(DishCommentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_comment
     *
     * @mbggenerated
     */
    int deleteByExample(DishCommentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_comment
     *
     * @mbggenerated
     */
    int insert(DishComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_comment
     *
     * @mbggenerated
     */
    int insertSelective(DishComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_comment
     *
     * @mbggenerated
     */
    List<DishComment> selectByExample(DishCommentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_comment
     *
     * @mbggenerated
     */
    DishComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_comment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DishComment record, @Param("example") DishCommentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_comment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DishComment record, @Param("example") DishCommentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DishComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DishComment record);
}