package com.yy.gameshop.dao;

import com.yy.gameshop.entity.ActivityInfo;
import com.yy.gameshop.entity.ActivityInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ActivityInfo
     *
     * @mbggenerated
     */
    int countByExample(ActivityInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ActivityInfo
     *
     * @mbggenerated
     */
    int deleteByExample(ActivityInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ActivityInfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ActivityInfo
     *
     * @mbggenerated
     */
    int insert(ActivityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ActivityInfo
     *
     * @mbggenerated
     */
    int insertSelective(ActivityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ActivityInfo
     *
     * @mbggenerated
     */
    List<ActivityInfo> selectByExample(ActivityInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ActivityInfo
     *
     * @mbggenerated
     */
    ActivityInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ActivityInfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ActivityInfo record, @Param("example") ActivityInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ActivityInfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ActivityInfo record, @Param("example") ActivityInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ActivityInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActivityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ActivityInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActivityInfo record);
}