package com.yy.gameshop.dao;

import com.yy.gameshop.entity.Bannner;
import com.yy.gameshop.entity.BannnerCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BannnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bannner
     *
     * @mbggenerated
     */
    int countByExample(BannnerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bannner
     *
     * @mbggenerated
     */
    int deleteByExample(BannnerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bannner
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bannner
     *
     * @mbggenerated
     */
    int insert(Bannner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bannner
     *
     * @mbggenerated
     */
    int insertSelective(Bannner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bannner
     *
     * @mbggenerated
     */
    List<Bannner> selectByExample(BannnerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bannner
     *
     * @mbggenerated
     */
    Bannner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bannner
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Bannner record, @Param("example") BannnerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bannner
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Bannner record, @Param("example") BannnerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bannner
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Bannner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Bannner
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Bannner record);
}