package com.yy.gameshop.dao;

import com.yy.gameshop.entity.Banner;
import com.yy.gameshop.entity.BannerCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Banner
     *
     * @mbggenerated
     */
    int countByExample(BannerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Banner
     *
     * @mbggenerated
     */
    int deleteByExample(BannerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Banner
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Banner
     *
     * @mbggenerated
     */
    int insert(Banner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Banner
     *
     * @mbggenerated
     */
    int insertSelective(Banner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Banner
     *
     * @mbggenerated
     */
    List<Banner> selectByExample(BannerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Banner
     *
     * @mbggenerated
     */
    Banner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Banner
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Banner record, @Param("example") BannerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Banner
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Banner record, @Param("example") BannerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Banner
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Banner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Banner
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Banner record);
}