package com.yy.gameshop.dao;

import com.yy.gameshop.entity.Category;
import com.yy.gameshop.entity.CategoryCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Category
     *
     * @mbggenerated
     */
    int countByExample(CategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Category
     *
     * @mbggenerated
     */
    int deleteByExample(CategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Category
     *
     * @mbggenerated
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Category
     *
     * @mbggenerated
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Category
     *
     * @mbggenerated
     */
    List<Category> selectByExample(CategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Category
     *
     * @mbggenerated
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Category record, @Param("example") CategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Category record, @Param("example") CategoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Category record);
}