package com.yy.gameshop.dao;

import com.yy.gameshop.entity.HotLabel;
import com.yy.gameshop.entity.HotLabelCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HotLabel
     *
     * @mbggenerated
     */
    int countByExample(HotLabelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HotLabel
     *
     * @mbggenerated
     */
    int deleteByExample(HotLabelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HotLabel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HotLabel
     *
     * @mbggenerated
     */
    int insert(HotLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HotLabel
     *
     * @mbggenerated
     */
    int insertSelective(HotLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HotLabel
     *
     * @mbggenerated
     */
    List<HotLabel> selectByExample(HotLabelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HotLabel
     *
     * @mbggenerated
     */
    HotLabel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HotLabel
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HotLabel record, @Param("example") HotLabelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HotLabel
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HotLabel record, @Param("example") HotLabelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HotLabel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HotLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HotLabel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HotLabel record);
}