package com.yy.gameshop.dao;

import com.yy.gameshop.entity.SubGame;
import com.yy.gameshop.entity.SubGameCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubGameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SubGame
     *
     * @mbggenerated
     */
    int countByExample(SubGameCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SubGame
     *
     * @mbggenerated
     */
    int deleteByExample(SubGameCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SubGame
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SubGame
     *
     * @mbggenerated
     */
    int insert(SubGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SubGame
     *
     * @mbggenerated
     */
    int insertSelective(SubGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SubGame
     *
     * @mbggenerated
     */
    List<SubGame> selectByExample(SubGameCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SubGame
     *
     * @mbggenerated
     */
    SubGame selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SubGame
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SubGame record, @Param("example") SubGameCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SubGame
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SubGame record, @Param("example") SubGameCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SubGame
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SubGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SubGame
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SubGame record);
}