package com.yy.shop.dao;

import com.yy.shop.entity.Area;
import com.yy.shop.entity.AreaCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Area
     *
     * @mbggenerated
     */
    int countByExample(AreaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Area
     *
     * @mbggenerated
     */
    int deleteByExample(AreaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Area
     *
     * @mbggenerated
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Area
     *
     * @mbggenerated
     */
    int insertSelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Area
     *
     * @mbggenerated
     */
    List<Area> selectByExample(AreaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Area
     *
     * @mbggenerated
     */
    Area selectByPrimaryKey(Integer areaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Area
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Area record, @Param("example") AreaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Area
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Area record, @Param("example") AreaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Area
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Area
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Area record);
}