package com.yy.userinfo.dao;

import com.yy.userinfo.entity.GoodReplyHistory;
import com.yy.userinfo.entity.GoodReplyHistoryCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodReplyHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_reply_history
     *
     * @mbggenerated
     */
    int countByExample(GoodReplyHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_reply_history
     *
     * @mbggenerated
     */
    int deleteByExample(GoodReplyHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_reply_history
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_reply_history
     *
     * @mbggenerated
     */
    int insert(GoodReplyHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_reply_history
     *
     * @mbggenerated
     */
    int insertSelective(GoodReplyHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_reply_history
     *
     * @mbggenerated
     */
    List<GoodReplyHistory> selectByExample(GoodReplyHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_reply_history
     *
     * @mbggenerated
     */
    GoodReplyHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_reply_history
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GoodReplyHistory record, @Param("example") GoodReplyHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_reply_history
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GoodReplyHistory record, @Param("example") GoodReplyHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_reply_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodReplyHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_reply_history
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodReplyHistory record);
}