package com.yy.wenjuan.dao;

import com.yy.wenjuan.entity.WenJuanEntity;
import com.yy.wenjuan.entity.WenJuanEntityCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WenJuanEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenjuan
     *
     * @mbggenerated
     */
    int countByExample(WenJuanEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenjuan
     *
     * @mbggenerated
     */
    int deleteByExample(WenJuanEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenjuan
     *
     * @mbggenerated
     */
    int insert(WenJuanEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenjuan
     *
     * @mbggenerated
     */
    int insertSelective(WenJuanEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenjuan
     *
     * @mbggenerated
     */
    List<WenJuanEntity> selectByExample(WenJuanEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenjuan
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WenJuanEntity record, @Param("example") WenJuanEntityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wenjuan
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WenJuanEntity record, @Param("example") WenJuanEntityCriteria example);
}