package com.yy.baby.fighting.dao;

import com.yy.baby.fighting.entity.MasterBaby;
import com.yy.baby.fighting.entity.MasterBabyCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MasterBabyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_baby
     *
     * @mbggenerated
     */
    int countByExample(MasterBabyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_baby
     *
     * @mbggenerated
     */
    int deleteByExample(MasterBabyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_baby
     *
     * @mbggenerated
     */
    int insert(MasterBaby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_baby
     *
     * @mbggenerated
     */
    int insertSelective(MasterBaby record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_baby
     *
     * @mbggenerated
     */
    List<MasterBaby> selectByExample(MasterBabyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_baby
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MasterBaby record, @Param("example") MasterBabyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_baby
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MasterBaby record, @Param("example") MasterBabyCriteria example);
}