package com.yy.baby.fighting.dao;

import com.yy.baby.fighting.entity.Msg3;
import com.yy.baby.fighting.entity.Msg3Criteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface Msg3Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_3
     *
     * @mbggenerated
     */
    int countByExample(Msg3Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_3
     *
     * @mbggenerated
     */
    int deleteByExample(Msg3Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_3
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_3
     *
     * @mbggenerated
     */
    int insert(Msg3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_3
     *
     * @mbggenerated
     */
    int insertSelective(Msg3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_3
     *
     * @mbggenerated
     */
    List<Msg3> selectByExample(Msg3Criteria example, RowBounds rowbounds);

    List<Msg3> selectByExampleWithBLOBs(Msg3Criteria example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_3
     *
     * @mbggenerated
     */
    List<Msg3> selectByExample(Msg3Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_3
     *
     * @mbggenerated
     */
    Msg3 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_3
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Msg3 record, @Param("example") Msg3Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_3
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Msg3 record, @Param("example") Msg3Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_3
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Msg3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_3
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Msg3 record);
}