package com.yy.baby.fighting.dao;

import com.yy.baby.fighting.entity.Msg9;
import com.yy.baby.fighting.entity.Msg9Criteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface Msg9Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_9
     *
     * @mbggenerated
     */
    int countByExample(Msg9Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_9
     *
     * @mbggenerated
     */
    int deleteByExample(Msg9Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_9
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_9
     *
     * @mbggenerated
     */
    int insert(Msg9 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_9
     *
     * @mbggenerated
     */
    int insertSelective(Msg9 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_9
     *
     * @mbggenerated
     */
    List<Msg9> selectByExample(Msg9Criteria example, RowBounds rowbounds);

    List<Msg9> selectByExampleWithBLOBs(Msg9Criteria example, RowBounds rowbounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_9
     *
     * @mbggenerated
     */
    List<Msg9> selectByExample(Msg9Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_9
     *
     * @mbggenerated
     */
    Msg9 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_9
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Msg9 record, @Param("example") Msg9Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_9
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Msg9 record, @Param("example") Msg9Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_9
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Msg9 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_9
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Msg9 record);
}