package com.yy.baby.fighting.entity;

public class MasterBaby {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_baby.masterUid
     *
     * @mbggenerated
     */
    private Long masterUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_baby.babyUid
     *
     * @mbggenerated
     */
    private Long babyUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_baby.babyNickName
     *
     * @mbggenerated
     */
    private String babyNickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_baby.babyYY
     *
     * @mbggenerated
     */
    private Long babyYY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column master_baby.babyIntimacy
     *
     * @mbggenerated
     */
    private Long babyIntimacy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_baby.masterUid
     *
     * @return the value of master_baby.masterUid
     *
     * @mbggenerated
     */
    public Long getMasterUid() {
        return masterUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_baby.masterUid
     *
     * @param masterUid the value for master_baby.masterUid
     *
     * @mbggenerated
     */
    public void setMasterUid(Long masterUid) {
        this.masterUid = masterUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_baby.babyUid
     *
     * @return the value of master_baby.babyUid
     *
     * @mbggenerated
     */
    public Long getBabyUid() {
        return babyUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_baby.babyUid
     *
     * @param babyUid the value for master_baby.babyUid
     *
     * @mbggenerated
     */
    public void setBabyUid(Long babyUid) {
        this.babyUid = babyUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_baby.babyNickName
     *
     * @return the value of master_baby.babyNickName
     *
     * @mbggenerated
     */
    public String getBabyNickName() {
        return babyNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_baby.babyNickName
     *
     * @param babyNickName the value for master_baby.babyNickName
     *
     * @mbggenerated
     */
    public void setBabyNickName(String babyNickName) {
        this.babyNickName = babyNickName == null ? null : babyNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_baby.babyYY
     *
     * @return the value of master_baby.babyYY
     *
     * @mbggenerated
     */
    public Long getBabyYY() {
        return babyYY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_baby.babyYY
     *
     * @param babyYY the value for master_baby.babyYY
     *
     * @mbggenerated
     */
    public void setBabyYY(Long babyYY) {
        this.babyYY = babyYY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column master_baby.babyIntimacy
     *
     * @return the value of master_baby.babyIntimacy
     *
     * @mbggenerated
     */
    public Long getBabyIntimacy() {
        return babyIntimacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column master_baby.babyIntimacy
     *
     * @param babyIntimacy the value for master_baby.babyIntimacy
     *
     * @mbggenerated
     */
    public void setBabyIntimacy(Long babyIntimacy) {
        this.babyIntimacy = babyIntimacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_baby
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MasterBaby other = (MasterBaby) that;
        return (this.getMasterUid() == null ? other.getMasterUid() == null : this.getMasterUid().equals(other.getMasterUid()))
            && (this.getBabyUid() == null ? other.getBabyUid() == null : this.getBabyUid().equals(other.getBabyUid()))
            && (this.getBabyNickName() == null ? other.getBabyNickName() == null : this.getBabyNickName().equals(other.getBabyNickName()))
            && (this.getBabyYY() == null ? other.getBabyYY() == null : this.getBabyYY().equals(other.getBabyYY()))
            && (this.getBabyIntimacy() == null ? other.getBabyIntimacy() == null : this.getBabyIntimacy().equals(other.getBabyIntimacy()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table master_baby
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMasterUid() == null) ? 0 : getMasterUid().hashCode());
        result = prime * result + ((getBabyUid() == null) ? 0 : getBabyUid().hashCode());
        result = prime * result + ((getBabyNickName() == null) ? 0 : getBabyNickName().hashCode());
        result = prime * result + ((getBabyYY() == null) ? 0 : getBabyYY().hashCode());
        result = prime * result + ((getBabyIntimacy() == null) ? 0 : getBabyIntimacy().hashCode());
        return result;
    }
}