package com.yy.baby.fighting.entity;

import java.util.Date;

public class Msg6 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_center_6.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_center_6.uid
     *
     * @mbggenerated
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_center_6.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_center_6.msg
     *
     * @mbggenerated
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg_center_6.add_time
     *
     * @mbggenerated
     */
    private Date add_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_center_6.id
     *
     * @return the value of msg_center_6.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_center_6.id
     *
     * @param id the value for msg_center_6.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_center_6.uid
     *
     * @return the value of msg_center_6.uid
     *
     * @mbggenerated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_center_6.uid
     *
     * @param uid the value for msg_center_6.uid
     *
     * @mbggenerated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_center_6.type
     *
     * @return the value of msg_center_6.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_center_6.type
     *
     * @param type the value for msg_center_6.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_center_6.msg
     *
     * @return the value of msg_center_6.msg
     *
     * @mbggenerated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_center_6.msg
     *
     * @param msg the value for msg_center_6.msg
     *
     * @mbggenerated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg_center_6.add_time
     *
     * @return the value of msg_center_6.add_time
     *
     * @mbggenerated
     */
    public Date getAdd_time() {
        return add_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg_center_6.add_time
     *
     * @param add_time the value for msg_center_6.add_time
     *
     * @mbggenerated
     */
    public void setAdd_time(Date add_time) {
        this.add_time = add_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_6
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Msg6 other = (Msg6) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getMsg() == null ? other.getMsg() == null : this.getMsg().equals(other.getMsg()))
            && (this.getAdd_time() == null ? other.getAdd_time() == null : this.getAdd_time().equals(other.getAdd_time()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_center_6
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getMsg() == null) ? 0 : getMsg().hashCode());
        result = prime * result + ((getAdd_time() == null) ? 0 : getAdd_time().hashCode());
        return result;
    }
}