package com.yy.rank.dao;

import com.yy.rank.entity.UserRank;
import com.yy.rank.entity.UserRankCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_userRank
     *
     * @mbggenerated
     */
    int countByExample(UserRankCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_userRank
     *
     * @mbggenerated
     */
    int deleteByExample(UserRankCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_userRank
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_userRank
     *
     * @mbggenerated
     */
    int insert(UserRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_userRank
     *
     * @mbggenerated
     */
    int insertSelective(UserRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_userRank
     *
     * @mbggenerated
     */
    List<UserRank> selectByExample(UserRankCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_userRank
     *
     * @mbggenerated
     */
    UserRank selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_userRank
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserRank record, @Param("example") UserRankCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_userRank
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserRank record, @Param("example") UserRankCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_userRank
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_userRank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRank record);
}