package com.yy.buy.mapper;

import com.yy.buy.domain.OrderMapper;
import com.yy.buy.domain.OrderMapperCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderMapperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_mapper
     *
     * @mbggenerated
     */
    int countByExample(OrderMapperCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_mapper
     *
     * @mbggenerated
     */
    int deleteByExample(OrderMapperCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_mapper
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long payOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_mapper
     *
     * @mbggenerated
     */
    int insertSelective(OrderMapper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_mapper
     *
     * @mbggenerated
     */
    List<OrderMapper> selectByExample(OrderMapperCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_mapper
     *
     * @mbggenerated
     */
    OrderMapper selectByPrimaryKey(Long payOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_mapper
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderMapper record, @Param("example") OrderMapperCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_mapper
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderMapper record);
}