package com.yy.gameshop.entity;

import java.util.Date;

public class ActivityInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ActivityInfo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ActivityInfo.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ActivityInfo.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ActivityInfo.startTime
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ActivityInfo.endTime
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ActivityInfo.isValid
     *
     * @mbggenerated
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ActivityInfo.gameCodes
     *
     * @mbggenerated
     */
    private String gameCodes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ActivityInfo.id
     *
     * @return the value of ActivityInfo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ActivityInfo.id
     *
     * @param id the value for ActivityInfo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ActivityInfo.type
     *
     * @return the value of ActivityInfo.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ActivityInfo.type
     *
     * @param type the value for ActivityInfo.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ActivityInfo.content
     *
     * @return the value of ActivityInfo.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ActivityInfo.content
     *
     * @param content the value for ActivityInfo.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ActivityInfo.startTime
     *
     * @return the value of ActivityInfo.startTime
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ActivityInfo.startTime
     *
     * @param startTime the value for ActivityInfo.startTime
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ActivityInfo.endTime
     *
     * @return the value of ActivityInfo.endTime
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ActivityInfo.endTime
     *
     * @param endTime the value for ActivityInfo.endTime
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ActivityInfo.isValid
     *
     * @return the value of ActivityInfo.isValid
     *
     * @mbggenerated
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ActivityInfo.isValid
     *
     * @param isValid the value for ActivityInfo.isValid
     *
     * @mbggenerated
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ActivityInfo.gameCodes
     *
     * @return the value of ActivityInfo.gameCodes
     *
     * @mbggenerated
     */
    public String getGameCodes() {
        return gameCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ActivityInfo.gameCodes
     *
     * @param gameCodes the value for ActivityInfo.gameCodes
     *
     * @mbggenerated
     */
    public void setGameCodes(String gameCodes) {
        this.gameCodes = gameCodes == null ? null : gameCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ActivityInfo
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ActivityInfo other = (ActivityInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getIsValid() == null ? other.getIsValid() == null : this.getIsValid().equals(other.getIsValid()))
            && (this.getGameCodes() == null ? other.getGameCodes() == null : this.getGameCodes().equals(other.getGameCodes()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ActivityInfo
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getIsValid() == null) ? 0 : getIsValid().hashCode());
        result = prime * result + ((getGameCodes() == null) ? 0 : getGameCodes().hashCode());
        return result;
    }
}