package com.yy.gameshop.entity;

import java.util.ArrayList;
import java.util.List;

public class GameInfoPicCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GameInfoPic
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GameInfoPic
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GameInfoPic
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GameInfoPic
     *
     * @mbggenerated
     */
    public GameInfoPicCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GameInfoPic
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GameInfoPic
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GameInfoPic
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GameInfoPic
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GameInfoPic
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GameInfoPic
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GameInfoPic
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GameInfoPic
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GameInfoPic
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GameInfoPic
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GameInfoPic
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGameCodeIsNull() {
            addCriterion("gameCode is null");
            return (Criteria) this;
        }

        public Criteria andGameCodeIsNotNull() {
            addCriterion("gameCode is not null");
            return (Criteria) this;
        }

        public Criteria andGameCodeEqualTo(String value) {
            addCriterion("gameCode =", value, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeNotEqualTo(String value) {
            addCriterion("gameCode <>", value, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeGreaterThan(String value) {
            addCriterion("gameCode >", value, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeGreaterThanOrEqualTo(String value) {
            addCriterion("gameCode >=", value, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeLessThan(String value) {
            addCriterion("gameCode <", value, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeLessThanOrEqualTo(String value) {
            addCriterion("gameCode <=", value, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeLike(String value) {
            addCriterion("gameCode like", value, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeNotLike(String value) {
            addCriterion("gameCode not like", value, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeIn(List<String> values) {
            addCriterion("gameCode in", values, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeNotIn(List<String> values) {
            addCriterion("gameCode not in", values, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeBetween(String value1, String value2) {
            addCriterion("gameCode between", value1, value2, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameCodeNotBetween(String value1, String value2) {
            addCriterion("gameCode not between", value1, value2, "gameCode");
            return (Criteria) this;
        }

        public Criteria andGameInfoPicUrlIsNull() {
            addCriterion("gameInfoPicUrl is null");
            return (Criteria) this;
        }

        public Criteria andGameInfoPicUrlIsNotNull() {
            addCriterion("gameInfoPicUrl is not null");
            return (Criteria) this;
        }

        public Criteria andGameInfoPicUrlEqualTo(String value) {
            addCriterion("gameInfoPicUrl =", value, "gameInfoPicUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoPicUrlNotEqualTo(String value) {
            addCriterion("gameInfoPicUrl <>", value, "gameInfoPicUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoPicUrlGreaterThan(String value) {
            addCriterion("gameInfoPicUrl >", value, "gameInfoPicUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoPicUrlGreaterThanOrEqualTo(String value) {
            addCriterion("gameInfoPicUrl >=", value, "gameInfoPicUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoPicUrlLessThan(String value) {
            addCriterion("gameInfoPicUrl <", value, "gameInfoPicUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoPicUrlLessThanOrEqualTo(String value) {
            addCriterion("gameInfoPicUrl <=", value, "gameInfoPicUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoPicUrlLike(String value) {
            addCriterion("gameInfoPicUrl like", value, "gameInfoPicUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoPicUrlNotLike(String value) {
            addCriterion("gameInfoPicUrl not like", value, "gameInfoPicUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoPicUrlIn(List<String> values) {
            addCriterion("gameInfoPicUrl in", values, "gameInfoPicUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoPicUrlNotIn(List<String> values) {
            addCriterion("gameInfoPicUrl not in", values, "gameInfoPicUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoPicUrlBetween(String value1, String value2) {
            addCriterion("gameInfoPicUrl between", value1, value2, "gameInfoPicUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoPicUrlNotBetween(String value1, String value2) {
            addCriterion("gameInfoPicUrl not between", value1, value2, "gameInfoPicUrl");
            return (Criteria) this;
        }

        public Criteria andVideoOrPicIsNull() {
            addCriterion("videoOrPic is null");
            return (Criteria) this;
        }

        public Criteria andVideoOrPicIsNotNull() {
            addCriterion("videoOrPic is not null");
            return (Criteria) this;
        }

        public Criteria andVideoOrPicEqualTo(Integer value) {
            addCriterion("videoOrPic =", value, "videoOrPic");
            return (Criteria) this;
        }

        public Criteria andVideoOrPicNotEqualTo(Integer value) {
            addCriterion("videoOrPic <>", value, "videoOrPic");
            return (Criteria) this;
        }

        public Criteria andVideoOrPicGreaterThan(Integer value) {
            addCriterion("videoOrPic >", value, "videoOrPic");
            return (Criteria) this;
        }

        public Criteria andVideoOrPicGreaterThanOrEqualTo(Integer value) {
            addCriterion("videoOrPic >=", value, "videoOrPic");
            return (Criteria) this;
        }

        public Criteria andVideoOrPicLessThan(Integer value) {
            addCriterion("videoOrPic <", value, "videoOrPic");
            return (Criteria) this;
        }

        public Criteria andVideoOrPicLessThanOrEqualTo(Integer value) {
            addCriterion("videoOrPic <=", value, "videoOrPic");
            return (Criteria) this;
        }

        public Criteria andVideoOrPicIn(List<Integer> values) {
            addCriterion("videoOrPic in", values, "videoOrPic");
            return (Criteria) this;
        }

        public Criteria andVideoOrPicNotIn(List<Integer> values) {
            addCriterion("videoOrPic not in", values, "videoOrPic");
            return (Criteria) this;
        }

        public Criteria andVideoOrPicBetween(Integer value1, Integer value2) {
            addCriterion("videoOrPic between", value1, value2, "videoOrPic");
            return (Criteria) this;
        }

        public Criteria andVideoOrPicNotBetween(Integer value1, Integer value2) {
            addCriterion("videoOrPic not between", value1, value2, "videoOrPic");
            return (Criteria) this;
        }

        public Criteria andGameInfoVideoUrlIsNull() {
            addCriterion("gameInfoVideoUrl is null");
            return (Criteria) this;
        }

        public Criteria andGameInfoVideoUrlIsNotNull() {
            addCriterion("gameInfoVideoUrl is not null");
            return (Criteria) this;
        }

        public Criteria andGameInfoVideoUrlEqualTo(String value) {
            addCriterion("gameInfoVideoUrl =", value, "gameInfoVideoUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoVideoUrlNotEqualTo(String value) {
            addCriterion("gameInfoVideoUrl <>", value, "gameInfoVideoUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoVideoUrlGreaterThan(String value) {
            addCriterion("gameInfoVideoUrl >", value, "gameInfoVideoUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoVideoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("gameInfoVideoUrl >=", value, "gameInfoVideoUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoVideoUrlLessThan(String value) {
            addCriterion("gameInfoVideoUrl <", value, "gameInfoVideoUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoVideoUrlLessThanOrEqualTo(String value) {
            addCriterion("gameInfoVideoUrl <=", value, "gameInfoVideoUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoVideoUrlLike(String value) {
            addCriterion("gameInfoVideoUrl like", value, "gameInfoVideoUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoVideoUrlNotLike(String value) {
            addCriterion("gameInfoVideoUrl not like", value, "gameInfoVideoUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoVideoUrlIn(List<String> values) {
            addCriterion("gameInfoVideoUrl in", values, "gameInfoVideoUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoVideoUrlNotIn(List<String> values) {
            addCriterion("gameInfoVideoUrl not in", values, "gameInfoVideoUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoVideoUrlBetween(String value1, String value2) {
            addCriterion("gameInfoVideoUrl between", value1, value2, "gameInfoVideoUrl");
            return (Criteria) this;
        }

        public Criteria andGameInfoVideoUrlNotBetween(String value1, String value2) {
            addCriterion("gameInfoVideoUrl not between", value1, value2, "gameInfoVideoUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GameInfoPic
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table GameInfoPic
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}