package com.yy.gameshop.entity;

public class NewGame {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NewGame.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NewGame.gamecode
     *
     * @mbggenerated
     */
    private String gamecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NewGame.gameName
     *
     * @mbggenerated
     */
    private String gameName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NewGame.hotValue
     *
     * @mbggenerated
     */
    private Long hotValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NewGame.downloadUrl
     *
     * @mbggenerated
     */
    private String downloadUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NewGame.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NewGame.valid
     *
     * @mbggenerated
     */
    private Integer valid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NewGame.id
     *
     * @return the value of NewGame.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NewGame.id
     *
     * @param id the value for NewGame.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NewGame.gamecode
     *
     * @return the value of NewGame.gamecode
     *
     * @mbggenerated
     */
    public String getGamecode() {
        return gamecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NewGame.gamecode
     *
     * @param gamecode the value for NewGame.gamecode
     *
     * @mbggenerated
     */
    public void setGamecode(String gamecode) {
        this.gamecode = gamecode == null ? null : gamecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NewGame.gameName
     *
     * @return the value of NewGame.gameName
     *
     * @mbggenerated
     */
    public String getGameName() {
        return gameName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NewGame.gameName
     *
     * @param gameName the value for NewGame.gameName
     *
     * @mbggenerated
     */
    public void setGameName(String gameName) {
        this.gameName = gameName == null ? null : gameName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NewGame.hotValue
     *
     * @return the value of NewGame.hotValue
     *
     * @mbggenerated
     */
    public Long getHotValue() {
        return hotValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NewGame.hotValue
     *
     * @param hotValue the value for NewGame.hotValue
     *
     * @mbggenerated
     */
    public void setHotValue(Long hotValue) {
        this.hotValue = hotValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NewGame.downloadUrl
     *
     * @return the value of NewGame.downloadUrl
     *
     * @mbggenerated
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NewGame.downloadUrl
     *
     * @param downloadUrl the value for NewGame.downloadUrl
     *
     * @mbggenerated
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl == null ? null : downloadUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NewGame.icon
     *
     * @return the value of NewGame.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NewGame.icon
     *
     * @param icon the value for NewGame.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NewGame.valid
     *
     * @return the value of NewGame.valid
     *
     * @mbggenerated
     */
    public Integer getValid() {
        return valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NewGame.valid
     *
     * @param valid the value for NewGame.valid
     *
     * @mbggenerated
     */
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NewGame
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NewGame other = (NewGame) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGamecode() == null ? other.getGamecode() == null : this.getGamecode().equals(other.getGamecode()))
            && (this.getGameName() == null ? other.getGameName() == null : this.getGameName().equals(other.getGameName()))
            && (this.getHotValue() == null ? other.getHotValue() == null : this.getHotValue().equals(other.getHotValue()))
            && (this.getDownloadUrl() == null ? other.getDownloadUrl() == null : this.getDownloadUrl().equals(other.getDownloadUrl()))
            && (this.getIcon() == null ? other.getIcon() == null : this.getIcon().equals(other.getIcon()))
            && (this.getValid() == null ? other.getValid() == null : this.getValid().equals(other.getValid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NewGame
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGamecode() == null) ? 0 : getGamecode().hashCode());
        result = prime * result + ((getGameName() == null) ? 0 : getGameName().hashCode());
        result = prime * result + ((getHotValue() == null) ? 0 : getHotValue().hashCode());
        result = prime * result + ((getDownloadUrl() == null) ? 0 : getDownloadUrl().hashCode());
        result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
        result = prime * result + ((getValid() == null) ? 0 : getValid().hashCode());
        return result;
    }
}