package com.afeiluo.cook.entity;

public class DishStep {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_step.dishId
     *
     * @mbggenerated
     */
    private Integer dishId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_step.stepDes
     *
     * @mbggenerated
     */
    private String stepDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_step.stepPic
     *
     * @mbggenerated
     */
    private String stepPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_step.stepNo
     *
     * @mbggenerated
     */
    private Integer stepNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_step.dishId
     *
     * @return the value of dish_step.dishId
     *
     * @mbggenerated
     */
    public Integer getDishId() {
        return dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_step.dishId
     *
     * @param dishId the value for dish_step.dishId
     *
     * @mbggenerated
     */
    public void setDishId(Integer dishId) {
        this.dishId = dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_step.stepDes
     *
     * @return the value of dish_step.stepDes
     *
     * @mbggenerated
     */
    public String getStepDes() {
        return stepDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_step.stepDes
     *
     * @param stepDes the value for dish_step.stepDes
     *
     * @mbggenerated
     */
    public void setStepDes(String stepDes) {
        this.stepDes = stepDes == null ? null : stepDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_step.stepPic
     *
     * @return the value of dish_step.stepPic
     *
     * @mbggenerated
     */
    public String getStepPic() {
        return stepPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_step.stepPic
     *
     * @param stepPic the value for dish_step.stepPic
     *
     * @mbggenerated
     */
    public void setStepPic(String stepPic) {
        this.stepPic = stepPic == null ? null : stepPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_step.stepNo
     *
     * @return the value of dish_step.stepNo
     *
     * @mbggenerated
     */
    public Integer getStepNo() {
        return stepNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_step.stepNo
     *
     * @param stepNo the value for dish_step.stepNo
     *
     * @mbggenerated
     */
    public void setStepNo(Integer stepNo) {
        this.stepNo = stepNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_step
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DishStep other = (DishStep) that;
        return (this.getDishId() == null ? other.getDishId() == null : this.getDishId().equals(other.getDishId()))
            && (this.getStepDes() == null ? other.getStepDes() == null : this.getStepDes().equals(other.getStepDes()))
            && (this.getStepPic() == null ? other.getStepPic() == null : this.getStepPic().equals(other.getStepPic()))
            && (this.getStepNo() == null ? other.getStepNo() == null : this.getStepNo().equals(other.getStepNo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_step
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDishId() == null) ? 0 : getDishId().hashCode());
        result = prime * result + ((getStepDes() == null) ? 0 : getStepDes().hashCode());
        result = prime * result + ((getStepPic() == null) ? 0 : getStepPic().hashCode());
        result = prime * result + ((getStepNo() == null) ? 0 : getStepNo().hashCode());
        return result;
    }
}