package com.yy.shop.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LiveCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table live
     *
     * @mbggenerated
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    public LiveCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table live
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLive_uidIsNull() {
            addCriterion("live_uid is null");
            return (Criteria) this;
        }

        public Criteria andLive_uidIsNotNull() {
            addCriterion("live_uid is not null");
            return (Criteria) this;
        }

        public Criteria andLive_uidEqualTo(Long value) {
            addCriterion("live_uid =", value, "live_uid");
            return (Criteria) this;
        }

        public Criteria andLive_uidNotEqualTo(Long value) {
            addCriterion("live_uid <>", value, "live_uid");
            return (Criteria) this;
        }

        public Criteria andLive_uidGreaterThan(Long value) {
            addCriterion("live_uid >", value, "live_uid");
            return (Criteria) this;
        }

        public Criteria andLive_uidGreaterThanOrEqualTo(Long value) {
            addCriterion("live_uid >=", value, "live_uid");
            return (Criteria) this;
        }

        public Criteria andLive_uidLessThan(Long value) {
            addCriterion("live_uid <", value, "live_uid");
            return (Criteria) this;
        }

        public Criteria andLive_uidLessThanOrEqualTo(Long value) {
            addCriterion("live_uid <=", value, "live_uid");
            return (Criteria) this;
        }

        public Criteria andLive_uidIn(List<Long> values) {
            addCriterion("live_uid in", values, "live_uid");
            return (Criteria) this;
        }

        public Criteria andLive_uidNotIn(List<Long> values) {
            addCriterion("live_uid not in", values, "live_uid");
            return (Criteria) this;
        }

        public Criteria andLive_uidBetween(Long value1, Long value2) {
            addCriterion("live_uid between", value1, value2, "live_uid");
            return (Criteria) this;
        }

        public Criteria andLive_uidNotBetween(Long value1, Long value2) {
            addCriterion("live_uid not between", value1, value2, "live_uid");
            return (Criteria) this;
        }

        public Criteria andSidIsNull() {
            addCriterion("sid is null");
            return (Criteria) this;
        }

        public Criteria andSidIsNotNull() {
            addCriterion("sid is not null");
            return (Criteria) this;
        }

        public Criteria andSidEqualTo(Long value) {
            addCriterion("sid =", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotEqualTo(Long value) {
            addCriterion("sid <>", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThan(Long value) {
            addCriterion("sid >", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThanOrEqualTo(Long value) {
            addCriterion("sid >=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThan(Long value) {
            addCriterion("sid <", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThanOrEqualTo(Long value) {
            addCriterion("sid <=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidIn(List<Long> values) {
            addCriterion("sid in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotIn(List<Long> values) {
            addCriterion("sid not in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidBetween(Long value1, Long value2) {
            addCriterion("sid between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotBetween(Long value1, Long value2) {
            addCriterion("sid not between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSsidIsNull() {
            addCriterion("ssid is null");
            return (Criteria) this;
        }

        public Criteria andSsidIsNotNull() {
            addCriterion("ssid is not null");
            return (Criteria) this;
        }

        public Criteria andSsidEqualTo(Long value) {
            addCriterion("ssid =", value, "ssid");
            return (Criteria) this;
        }

        public Criteria andSsidNotEqualTo(Long value) {
            addCriterion("ssid <>", value, "ssid");
            return (Criteria) this;
        }

        public Criteria andSsidGreaterThan(Long value) {
            addCriterion("ssid >", value, "ssid");
            return (Criteria) this;
        }

        public Criteria andSsidGreaterThanOrEqualTo(Long value) {
            addCriterion("ssid >=", value, "ssid");
            return (Criteria) this;
        }

        public Criteria andSsidLessThan(Long value) {
            addCriterion("ssid <", value, "ssid");
            return (Criteria) this;
        }

        public Criteria andSsidLessThanOrEqualTo(Long value) {
            addCriterion("ssid <=", value, "ssid");
            return (Criteria) this;
        }

        public Criteria andSsidIn(List<Long> values) {
            addCriterion("ssid in", values, "ssid");
            return (Criteria) this;
        }

        public Criteria andSsidNotIn(List<Long> values) {
            addCriterion("ssid not in", values, "ssid");
            return (Criteria) this;
        }

        public Criteria andSsidBetween(Long value1, Long value2) {
            addCriterion("ssid between", value1, value2, "ssid");
            return (Criteria) this;
        }

        public Criteria andSsidNotBetween(Long value1, Long value2) {
            addCriterion("ssid not between", value1, value2, "ssid");
            return (Criteria) this;
        }

        public Criteria andStart_timeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStart_timeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStart_timeEqualTo(Long value) {
            addCriterion("start_time =", value, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeNotEqualTo(Long value) {
            addCriterion("start_time <>", value, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeGreaterThan(Long value) {
            addCriterion("start_time >", value, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeGreaterThanOrEqualTo(Long value) {
            addCriterion("start_time >=", value, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeLessThan(Long value) {
            addCriterion("start_time <", value, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeLessThanOrEqualTo(Long value) {
            addCriterion("start_time <=", value, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeIn(List<Long> values) {
            addCriterion("start_time in", values, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeNotIn(List<Long> values) {
            addCriterion("start_time not in", values, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeBetween(Long value1, Long value2) {
            addCriterion("start_time between", value1, value2, "start_time");
            return (Criteria) this;
        }

        public Criteria andStart_timeNotBetween(Long value1, Long value2) {
            addCriterion("start_time not between", value1, value2, "start_time");
            return (Criteria) this;
        }

        public Criteria andLast_updateIsNull() {
            addCriterion("last_update is null");
            return (Criteria) this;
        }

        public Criteria andLast_updateIsNotNull() {
            addCriterion("last_update is not null");
            return (Criteria) this;
        }

        public Criteria andLast_updateEqualTo(Date value) {
            addCriterion("last_update =", value, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateNotEqualTo(Date value) {
            addCriterion("last_update <>", value, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateGreaterThan(Date value) {
            addCriterion("last_update >", value, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update >=", value, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateLessThan(Date value) {
            addCriterion("last_update <", value, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateLessThanOrEqualTo(Date value) {
            addCriterion("last_update <=", value, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateIn(List<Date> values) {
            addCriterion("last_update in", values, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateNotIn(List<Date> values) {
            addCriterion("last_update not in", values, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateBetween(Date value1, Date value2) {
            addCriterion("last_update between", value1, value2, "last_update");
            return (Criteria) this;
        }

        public Criteria andLast_updateNotBetween(Date value1, Date value2) {
            addCriterion("last_update not between", value1, value2, "last_update");
            return (Criteria) this;
        }

        public Criteria andChannel_nameIsNull() {
            addCriterion("channel_name is null");
            return (Criteria) this;
        }

        public Criteria andChannel_nameIsNotNull() {
            addCriterion("channel_name is not null");
            return (Criteria) this;
        }

        public Criteria andChannel_nameEqualTo(String value) {
            addCriterion("channel_name =", value, "channel_name");
            return (Criteria) this;
        }

        public Criteria andChannel_nameNotEqualTo(String value) {
            addCriterion("channel_name <>", value, "channel_name");
            return (Criteria) this;
        }

        public Criteria andChannel_nameGreaterThan(String value) {
            addCriterion("channel_name >", value, "channel_name");
            return (Criteria) this;
        }

        public Criteria andChannel_nameGreaterThanOrEqualTo(String value) {
            addCriterion("channel_name >=", value, "channel_name");
            return (Criteria) this;
        }

        public Criteria andChannel_nameLessThan(String value) {
            addCriterion("channel_name <", value, "channel_name");
            return (Criteria) this;
        }

        public Criteria andChannel_nameLessThanOrEqualTo(String value) {
            addCriterion("channel_name <=", value, "channel_name");
            return (Criteria) this;
        }

        public Criteria andChannel_nameLike(String value) {
            addCriterion("channel_name like", value, "channel_name");
            return (Criteria) this;
        }

        public Criteria andChannel_nameNotLike(String value) {
            addCriterion("channel_name not like", value, "channel_name");
            return (Criteria) this;
        }

        public Criteria andChannel_nameIn(List<String> values) {
            addCriterion("channel_name in", values, "channel_name");
            return (Criteria) this;
        }

        public Criteria andChannel_nameNotIn(List<String> values) {
            addCriterion("channel_name not in", values, "channel_name");
            return (Criteria) this;
        }

        public Criteria andChannel_nameBetween(String value1, String value2) {
            addCriterion("channel_name between", value1, value2, "channel_name");
            return (Criteria) this;
        }

        public Criteria andChannel_nameNotBetween(String value1, String value2) {
            addCriterion("channel_name not between", value1, value2, "channel_name");
            return (Criteria) this;
        }

        public Criteria andThumbIsNull() {
            addCriterion("thumb is null");
            return (Criteria) this;
        }

        public Criteria andThumbIsNotNull() {
            addCriterion("thumb is not null");
            return (Criteria) this;
        }

        public Criteria andThumbEqualTo(String value) {
            addCriterion("thumb =", value, "thumb");
            return (Criteria) this;
        }

        public Criteria andThumbNotEqualTo(String value) {
            addCriterion("thumb <>", value, "thumb");
            return (Criteria) this;
        }

        public Criteria andThumbGreaterThan(String value) {
            addCriterion("thumb >", value, "thumb");
            return (Criteria) this;
        }

        public Criteria andThumbGreaterThanOrEqualTo(String value) {
            addCriterion("thumb >=", value, "thumb");
            return (Criteria) this;
        }

        public Criteria andThumbLessThan(String value) {
            addCriterion("thumb <", value, "thumb");
            return (Criteria) this;
        }

        public Criteria andThumbLessThanOrEqualTo(String value) {
            addCriterion("thumb <=", value, "thumb");
            return (Criteria) this;
        }

        public Criteria andThumbLike(String value) {
            addCriterion("thumb like", value, "thumb");
            return (Criteria) this;
        }

        public Criteria andThumbNotLike(String value) {
            addCriterion("thumb not like", value, "thumb");
            return (Criteria) this;
        }

        public Criteria andThumbIn(List<String> values) {
            addCriterion("thumb in", values, "thumb");
            return (Criteria) this;
        }

        public Criteria andThumbNotIn(List<String> values) {
            addCriterion("thumb not in", values, "thumb");
            return (Criteria) this;
        }

        public Criteria andThumbBetween(String value1, String value2) {
            addCriterion("thumb between", value1, value2, "thumb");
            return (Criteria) this;
        }

        public Criteria andThumbNotBetween(String value1, String value2) {
            addCriterion("thumb not between", value1, value2, "thumb");
            return (Criteria) this;
        }

        public Criteria andLive_nameIsNull() {
            addCriterion("live_name is null");
            return (Criteria) this;
        }

        public Criteria andLive_nameIsNotNull() {
            addCriterion("live_name is not null");
            return (Criteria) this;
        }

        public Criteria andLive_nameEqualTo(String value) {
            addCriterion("live_name =", value, "live_name");
            return (Criteria) this;
        }

        public Criteria andLive_nameNotEqualTo(String value) {
            addCriterion("live_name <>", value, "live_name");
            return (Criteria) this;
        }

        public Criteria andLive_nameGreaterThan(String value) {
            addCriterion("live_name >", value, "live_name");
            return (Criteria) this;
        }

        public Criteria andLive_nameGreaterThanOrEqualTo(String value) {
            addCriterion("live_name >=", value, "live_name");
            return (Criteria) this;
        }

        public Criteria andLive_nameLessThan(String value) {
            addCriterion("live_name <", value, "live_name");
            return (Criteria) this;
        }

        public Criteria andLive_nameLessThanOrEqualTo(String value) {
            addCriterion("live_name <=", value, "live_name");
            return (Criteria) this;
        }

        public Criteria andLive_nameLike(String value) {
            addCriterion("live_name like", value, "live_name");
            return (Criteria) this;
        }

        public Criteria andLive_nameNotLike(String value) {
            addCriterion("live_name not like", value, "live_name");
            return (Criteria) this;
        }

        public Criteria andLive_nameIn(List<String> values) {
            addCriterion("live_name in", values, "live_name");
            return (Criteria) this;
        }

        public Criteria andLive_nameNotIn(List<String> values) {
            addCriterion("live_name not in", values, "live_name");
            return (Criteria) this;
        }

        public Criteria andLive_nameBetween(String value1, String value2) {
            addCriterion("live_name between", value1, value2, "live_name");
            return (Criteria) this;
        }

        public Criteria andLive_nameNotBetween(String value1, String value2) {
            addCriterion("live_name not between", value1, value2, "live_name");
            return (Criteria) this;
        }

        public Criteria andLive_timeIsNull() {
            addCriterion("live_time is null");
            return (Criteria) this;
        }

        public Criteria andLive_timeIsNotNull() {
            addCriterion("live_time is not null");
            return (Criteria) this;
        }

        public Criteria andLive_timeEqualTo(Long value) {
            addCriterion("live_time =", value, "live_time");
            return (Criteria) this;
        }

        public Criteria andLive_timeNotEqualTo(Long value) {
            addCriterion("live_time <>", value, "live_time");
            return (Criteria) this;
        }

        public Criteria andLive_timeGreaterThan(Long value) {
            addCriterion("live_time >", value, "live_time");
            return (Criteria) this;
        }

        public Criteria andLive_timeGreaterThanOrEqualTo(Long value) {
            addCriterion("live_time >=", value, "live_time");
            return (Criteria) this;
        }

        public Criteria andLive_timeLessThan(Long value) {
            addCriterion("live_time <", value, "live_time");
            return (Criteria) this;
        }

        public Criteria andLive_timeLessThanOrEqualTo(Long value) {
            addCriterion("live_time <=", value, "live_time");
            return (Criteria) this;
        }

        public Criteria andLive_timeIn(List<Long> values) {
            addCriterion("live_time in", values, "live_time");
            return (Criteria) this;
        }

        public Criteria andLive_timeNotIn(List<Long> values) {
            addCriterion("live_time not in", values, "live_time");
            return (Criteria) this;
        }

        public Criteria andLive_timeBetween(Long value1, Long value2) {
            addCriterion("live_time between", value1, value2, "live_time");
            return (Criteria) this;
        }

        public Criteria andLive_timeNotBetween(Long value1, Long value2) {
            addCriterion("live_time not between", value1, value2, "live_time");
            return (Criteria) this;
        }

        public Criteria andUsersIsNull() {
            addCriterion("users is null");
            return (Criteria) this;
        }

        public Criteria andUsersIsNotNull() {
            addCriterion("users is not null");
            return (Criteria) this;
        }

        public Criteria andUsersEqualTo(Integer value) {
            addCriterion("users =", value, "users");
            return (Criteria) this;
        }

        public Criteria andUsersNotEqualTo(Integer value) {
            addCriterion("users <>", value, "users");
            return (Criteria) this;
        }

        public Criteria andUsersGreaterThan(Integer value) {
            addCriterion("users >", value, "users");
            return (Criteria) this;
        }

        public Criteria andUsersGreaterThanOrEqualTo(Integer value) {
            addCriterion("users >=", value, "users");
            return (Criteria) this;
        }

        public Criteria andUsersLessThan(Integer value) {
            addCriterion("users <", value, "users");
            return (Criteria) this;
        }

        public Criteria andUsersLessThanOrEqualTo(Integer value) {
            addCriterion("users <=", value, "users");
            return (Criteria) this;
        }

        public Criteria andUsersIn(List<Integer> values) {
            addCriterion("users in", values, "users");
            return (Criteria) this;
        }

        public Criteria andUsersNotIn(List<Integer> values) {
            addCriterion("users not in", values, "users");
            return (Criteria) this;
        }

        public Criteria andUsersBetween(Integer value1, Integer value2) {
            addCriterion("users between", value1, value2, "users");
            return (Criteria) this;
        }

        public Criteria andUsersNotBetween(Integer value1, Integer value2) {
            addCriterion("users not between", value1, value2, "users");
            return (Criteria) this;
        }

        public Criteria andLimit_countIsNull() {
            addCriterion("limit_count is null");
            return (Criteria) this;
        }

        public Criteria andLimit_countIsNotNull() {
            addCriterion("limit_count is not null");
            return (Criteria) this;
        }

        public Criteria andLimit_countEqualTo(Integer value) {
            addCriterion("limit_count =", value, "limit_count");
            return (Criteria) this;
        }

        public Criteria andLimit_countNotEqualTo(Integer value) {
            addCriterion("limit_count <>", value, "limit_count");
            return (Criteria) this;
        }

        public Criteria andLimit_countGreaterThan(Integer value) {
            addCriterion("limit_count >", value, "limit_count");
            return (Criteria) this;
        }

        public Criteria andLimit_countGreaterThanOrEqualTo(Integer value) {
            addCriterion("limit_count >=", value, "limit_count");
            return (Criteria) this;
        }

        public Criteria andLimit_countLessThan(Integer value) {
            addCriterion("limit_count <", value, "limit_count");
            return (Criteria) this;
        }

        public Criteria andLimit_countLessThanOrEqualTo(Integer value) {
            addCriterion("limit_count <=", value, "limit_count");
            return (Criteria) this;
        }

        public Criteria andLimit_countIn(List<Integer> values) {
            addCriterion("limit_count in", values, "limit_count");
            return (Criteria) this;
        }

        public Criteria andLimit_countNotIn(List<Integer> values) {
            addCriterion("limit_count not in", values, "limit_count");
            return (Criteria) this;
        }

        public Criteria andLimit_countBetween(Integer value1, Integer value2) {
            addCriterion("limit_count between", value1, value2, "limit_count");
            return (Criteria) this;
        }

        public Criteria andLimit_countNotBetween(Integer value1, Integer value2) {
            addCriterion("limit_count not between", value1, value2, "limit_count");
            return (Criteria) this;
        }

        public Criteria andIs_recommendIsNull() {
            addCriterion("is_recommend is null");
            return (Criteria) this;
        }

        public Criteria andIs_recommendIsNotNull() {
            addCriterion("is_recommend is not null");
            return (Criteria) this;
        }

        public Criteria andIs_recommendEqualTo(Byte value) {
            addCriterion("is_recommend =", value, "is_recommend");
            return (Criteria) this;
        }

        public Criteria andIs_recommendNotEqualTo(Byte value) {
            addCriterion("is_recommend <>", value, "is_recommend");
            return (Criteria) this;
        }

        public Criteria andIs_recommendGreaterThan(Byte value) {
            addCriterion("is_recommend >", value, "is_recommend");
            return (Criteria) this;
        }

        public Criteria andIs_recommendGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_recommend >=", value, "is_recommend");
            return (Criteria) this;
        }

        public Criteria andIs_recommendLessThan(Byte value) {
            addCriterion("is_recommend <", value, "is_recommend");
            return (Criteria) this;
        }

        public Criteria andIs_recommendLessThanOrEqualTo(Byte value) {
            addCriterion("is_recommend <=", value, "is_recommend");
            return (Criteria) this;
        }

        public Criteria andIs_recommendIn(List<Byte> values) {
            addCriterion("is_recommend in", values, "is_recommend");
            return (Criteria) this;
        }

        public Criteria andIs_recommendNotIn(List<Byte> values) {
            addCriterion("is_recommend not in", values, "is_recommend");
            return (Criteria) this;
        }

        public Criteria andIs_recommendBetween(Byte value1, Byte value2) {
            addCriterion("is_recommend between", value1, value2, "is_recommend");
            return (Criteria) this;
        }

        public Criteria andIs_recommendNotBetween(Byte value1, Byte value2) {
            addCriterion("is_recommend not between", value1, value2, "is_recommend");
            return (Criteria) this;
        }

        public Criteria andTabidIsNull() {
            addCriterion("tabid is null");
            return (Criteria) this;
        }

        public Criteria andTabidIsNotNull() {
            addCriterion("tabid is not null");
            return (Criteria) this;
        }

        public Criteria andTabidEqualTo(Integer value) {
            addCriterion("tabid =", value, "tabid");
            return (Criteria) this;
        }

        public Criteria andTabidNotEqualTo(Integer value) {
            addCriterion("tabid <>", value, "tabid");
            return (Criteria) this;
        }

        public Criteria andTabidGreaterThan(Integer value) {
            addCriterion("tabid >", value, "tabid");
            return (Criteria) this;
        }

        public Criteria andTabidGreaterThanOrEqualTo(Integer value) {
            addCriterion("tabid >=", value, "tabid");
            return (Criteria) this;
        }

        public Criteria andTabidLessThan(Integer value) {
            addCriterion("tabid <", value, "tabid");
            return (Criteria) this;
        }

        public Criteria andTabidLessThanOrEqualTo(Integer value) {
            addCriterion("tabid <=", value, "tabid");
            return (Criteria) this;
        }

        public Criteria andTabidIn(List<Integer> values) {
            addCriterion("tabid in", values, "tabid");
            return (Criteria) this;
        }

        public Criteria andTabidNotIn(List<Integer> values) {
            addCriterion("tabid not in", values, "tabid");
            return (Criteria) this;
        }

        public Criteria andTabidBetween(Integer value1, Integer value2) {
            addCriterion("tabid between", value1, value2, "tabid");
            return (Criteria) this;
        }

        public Criteria andTabidNotBetween(Integer value1, Integer value2) {
            addCriterion("tabid not between", value1, value2, "tabid");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTemplate_idIsNull() {
            addCriterion("template_id is null");
            return (Criteria) this;
        }

        public Criteria andTemplate_idIsNotNull() {
            addCriterion("template_id is not null");
            return (Criteria) this;
        }

        public Criteria andTemplate_idEqualTo(Long value) {
            addCriterion("template_id =", value, "template_id");
            return (Criteria) this;
        }

        public Criteria andTemplate_idNotEqualTo(Long value) {
            addCriterion("template_id <>", value, "template_id");
            return (Criteria) this;
        }

        public Criteria andTemplate_idGreaterThan(Long value) {
            addCriterion("template_id >", value, "template_id");
            return (Criteria) this;
        }

        public Criteria andTemplate_idGreaterThanOrEqualTo(Long value) {
            addCriterion("template_id >=", value, "template_id");
            return (Criteria) this;
        }

        public Criteria andTemplate_idLessThan(Long value) {
            addCriterion("template_id <", value, "template_id");
            return (Criteria) this;
        }

        public Criteria andTemplate_idLessThanOrEqualTo(Long value) {
            addCriterion("template_id <=", value, "template_id");
            return (Criteria) this;
        }

        public Criteria andTemplate_idIn(List<Long> values) {
            addCriterion("template_id in", values, "template_id");
            return (Criteria) this;
        }

        public Criteria andTemplate_idNotIn(List<Long> values) {
            addCriterion("template_id not in", values, "template_id");
            return (Criteria) this;
        }

        public Criteria andTemplate_idBetween(Long value1, Long value2) {
            addCriterion("template_id between", value1, value2, "template_id");
            return (Criteria) this;
        }

        public Criteria andTemplate_idNotBetween(Long value1, Long value2) {
            addCriterion("template_id not between", value1, value2, "template_id");
            return (Criteria) this;
        }

        public Criteria andLive_idIsNull() {
            addCriterion("live_id is null");
            return (Criteria) this;
        }

        public Criteria andLive_idIsNotNull() {
            addCriterion("live_id is not null");
            return (Criteria) this;
        }

        public Criteria andLive_idEqualTo(String value) {
            addCriterion("live_id =", value, "live_id");
            return (Criteria) this;
        }

        public Criteria andLive_idNotEqualTo(String value) {
            addCriterion("live_id <>", value, "live_id");
            return (Criteria) this;
        }

        public Criteria andLive_idGreaterThan(String value) {
            addCriterion("live_id >", value, "live_id");
            return (Criteria) this;
        }

        public Criteria andLive_idGreaterThanOrEqualTo(String value) {
            addCriterion("live_id >=", value, "live_id");
            return (Criteria) this;
        }

        public Criteria andLive_idLessThan(String value) {
            addCriterion("live_id <", value, "live_id");
            return (Criteria) this;
        }

        public Criteria andLive_idLessThanOrEqualTo(String value) {
            addCriterion("live_id <=", value, "live_id");
            return (Criteria) this;
        }

        public Criteria andLive_idLike(String value) {
            addCriterion("live_id like", value, "live_id");
            return (Criteria) this;
        }

        public Criteria andLive_idNotLike(String value) {
            addCriterion("live_id not like", value, "live_id");
            return (Criteria) this;
        }

        public Criteria andLive_idIn(List<String> values) {
            addCriterion("live_id in", values, "live_id");
            return (Criteria) this;
        }

        public Criteria andLive_idNotIn(List<String> values) {
            addCriterion("live_id not in", values, "live_id");
            return (Criteria) this;
        }

        public Criteria andLive_idBetween(String value1, String value2) {
            addCriterion("live_id between", value1, value2, "live_id");
            return (Criteria) this;
        }

        public Criteria andLive_idNotBetween(String value1, String value2) {
            addCriterion("live_id not between", value1, value2, "live_id");
            return (Criteria) this;
        }

        public Criteria andTagIsNull() {
            addCriterion("tag is null");
            return (Criteria) this;
        }

        public Criteria andTagIsNotNull() {
            addCriterion("tag is not null");
            return (Criteria) this;
        }

        public Criteria andTagEqualTo(String value) {
            addCriterion("tag =", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotEqualTo(String value) {
            addCriterion("tag <>", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagGreaterThan(String value) {
            addCriterion("tag >", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagGreaterThanOrEqualTo(String value) {
            addCriterion("tag >=", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLessThan(String value) {
            addCriterion("tag <", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLessThanOrEqualTo(String value) {
            addCriterion("tag <=", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLike(String value) {
            addCriterion("tag like", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotLike(String value) {
            addCriterion("tag not like", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagIn(List<String> values) {
            addCriterion("tag in", values, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotIn(List<String> values) {
            addCriterion("tag not in", values, "tag");
            return (Criteria) this;
        }

        public Criteria andTagBetween(String value1, String value2) {
            addCriterion("tag between", value1, value2, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotBetween(String value1, String value2) {
            addCriterion("tag not between", value1, value2, "tag");
            return (Criteria) this;
        }

        public Criteria andLast_update_serIsNull() {
            addCriterion("last_update_ser is null");
            return (Criteria) this;
        }

        public Criteria andLast_update_serIsNotNull() {
            addCriterion("last_update_ser is not null");
            return (Criteria) this;
        }

        public Criteria andLast_update_serEqualTo(Long value) {
            addCriterion("last_update_ser =", value, "last_update_ser");
            return (Criteria) this;
        }

        public Criteria andLast_update_serNotEqualTo(Long value) {
            addCriterion("last_update_ser <>", value, "last_update_ser");
            return (Criteria) this;
        }

        public Criteria andLast_update_serGreaterThan(Long value) {
            addCriterion("last_update_ser >", value, "last_update_ser");
            return (Criteria) this;
        }

        public Criteria andLast_update_serGreaterThanOrEqualTo(Long value) {
            addCriterion("last_update_ser >=", value, "last_update_ser");
            return (Criteria) this;
        }

        public Criteria andLast_update_serLessThan(Long value) {
            addCriterion("last_update_ser <", value, "last_update_ser");
            return (Criteria) this;
        }

        public Criteria andLast_update_serLessThanOrEqualTo(Long value) {
            addCriterion("last_update_ser <=", value, "last_update_ser");
            return (Criteria) this;
        }

        public Criteria andLast_update_serIn(List<Long> values) {
            addCriterion("last_update_ser in", values, "last_update_ser");
            return (Criteria) this;
        }

        public Criteria andLast_update_serNotIn(List<Long> values) {
            addCriterion("last_update_ser not in", values, "last_update_ser");
            return (Criteria) this;
        }

        public Criteria andLast_update_serBetween(Long value1, Long value2) {
            addCriterion("last_update_ser between", value1, value2, "last_update_ser");
            return (Criteria) this;
        }

        public Criteria andLast_update_serNotBetween(Long value1, Long value2) {
            addCriterion("last_update_ser not between", value1, value2, "last_update_ser");
            return (Criteria) this;
        }

        public Criteria andMulti_screenIsNull() {
            addCriterion("multi_screen is null");
            return (Criteria) this;
        }

        public Criteria andMulti_screenIsNotNull() {
            addCriterion("multi_screen is not null");
            return (Criteria) this;
        }

        public Criteria andMulti_screenEqualTo(String value) {
            addCriterion("multi_screen =", value, "multi_screen");
            return (Criteria) this;
        }

        public Criteria andMulti_screenNotEqualTo(String value) {
            addCriterion("multi_screen <>", value, "multi_screen");
            return (Criteria) this;
        }

        public Criteria andMulti_screenGreaterThan(String value) {
            addCriterion("multi_screen >", value, "multi_screen");
            return (Criteria) this;
        }

        public Criteria andMulti_screenGreaterThanOrEqualTo(String value) {
            addCriterion("multi_screen >=", value, "multi_screen");
            return (Criteria) this;
        }

        public Criteria andMulti_screenLessThan(String value) {
            addCriterion("multi_screen <", value, "multi_screen");
            return (Criteria) this;
        }

        public Criteria andMulti_screenLessThanOrEqualTo(String value) {
            addCriterion("multi_screen <=", value, "multi_screen");
            return (Criteria) this;
        }

        public Criteria andMulti_screenLike(String value) {
            addCriterion("multi_screen like", value, "multi_screen");
            return (Criteria) this;
        }

        public Criteria andMulti_screenNotLike(String value) {
            addCriterion("multi_screen not like", value, "multi_screen");
            return (Criteria) this;
        }

        public Criteria andMulti_screenIn(List<String> values) {
            addCriterion("multi_screen in", values, "multi_screen");
            return (Criteria) this;
        }

        public Criteria andMulti_screenNotIn(List<String> values) {
            addCriterion("multi_screen not in", values, "multi_screen");
            return (Criteria) this;
        }

        public Criteria andMulti_screenBetween(String value1, String value2) {
            addCriterion("multi_screen between", value1, value2, "multi_screen");
            return (Criteria) this;
        }

        public Criteria andMulti_screenNotBetween(String value1, String value2) {
            addCriterion("multi_screen not between", value1, value2, "multi_screen");
            return (Criteria) this;
        }

        public Criteria andHotIsNull() {
            addCriterion("hot is null");
            return (Criteria) this;
        }

        public Criteria andHotIsNotNull() {
            addCriterion("hot is not null");
            return (Criteria) this;
        }

        public Criteria andHotEqualTo(Integer value) {
            addCriterion("hot =", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotNotEqualTo(Integer value) {
            addCriterion("hot <>", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotGreaterThan(Integer value) {
            addCriterion("hot >", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotGreaterThanOrEqualTo(Integer value) {
            addCriterion("hot >=", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotLessThan(Integer value) {
            addCriterion("hot <", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotLessThanOrEqualTo(Integer value) {
            addCriterion("hot <=", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotIn(List<Integer> values) {
            addCriterion("hot in", values, "hot");
            return (Criteria) this;
        }

        public Criteria andHotNotIn(List<Integer> values) {
            addCriterion("hot not in", values, "hot");
            return (Criteria) this;
        }

        public Criteria andHotBetween(Integer value1, Integer value2) {
            addCriterion("hot between", value1, value2, "hot");
            return (Criteria) this;
        }

        public Criteria andHotNotBetween(Integer value1, Integer value2) {
            addCriterion("hot not between", value1, value2, "hot");
            return (Criteria) this;
        }

        public Criteria andAppidIsNull() {
            addCriterion("appid is null");
            return (Criteria) this;
        }

        public Criteria andAppidIsNotNull() {
            addCriterion("appid is not null");
            return (Criteria) this;
        }

        public Criteria andAppidEqualTo(Long value) {
            addCriterion("appid =", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotEqualTo(Long value) {
            addCriterion("appid <>", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThan(Long value) {
            addCriterion("appid >", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThanOrEqualTo(Long value) {
            addCriterion("appid >=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThan(Long value) {
            addCriterion("appid <", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThanOrEqualTo(Long value) {
            addCriterion("appid <=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidIn(List<Long> values) {
            addCriterion("appid in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotIn(List<Long> values) {
            addCriterion("appid not in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidBetween(Long value1, Long value2) {
            addCriterion("appid between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotBetween(Long value1, Long value2) {
            addCriterion("appid not between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andFrom_typeIsNull() {
            addCriterion("from_type is null");
            return (Criteria) this;
        }

        public Criteria andFrom_typeIsNotNull() {
            addCriterion("from_type is not null");
            return (Criteria) this;
        }

        public Criteria andFrom_typeEqualTo(Integer value) {
            addCriterion("from_type =", value, "from_type");
            return (Criteria) this;
        }

        public Criteria andFrom_typeNotEqualTo(Integer value) {
            addCriterion("from_type <>", value, "from_type");
            return (Criteria) this;
        }

        public Criteria andFrom_typeGreaterThan(Integer value) {
            addCriterion("from_type >", value, "from_type");
            return (Criteria) this;
        }

        public Criteria andFrom_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("from_type >=", value, "from_type");
            return (Criteria) this;
        }

        public Criteria andFrom_typeLessThan(Integer value) {
            addCriterion("from_type <", value, "from_type");
            return (Criteria) this;
        }

        public Criteria andFrom_typeLessThanOrEqualTo(Integer value) {
            addCriterion("from_type <=", value, "from_type");
            return (Criteria) this;
        }

        public Criteria andFrom_typeIn(List<Integer> values) {
            addCriterion("from_type in", values, "from_type");
            return (Criteria) this;
        }

        public Criteria andFrom_typeNotIn(List<Integer> values) {
            addCriterion("from_type not in", values, "from_type");
            return (Criteria) this;
        }

        public Criteria andFrom_typeBetween(Integer value1, Integer value2) {
            addCriterion("from_type between", value1, value2, "from_type");
            return (Criteria) this;
        }

        public Criteria andFrom_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("from_type not between", value1, value2, "from_type");
            return (Criteria) this;
        }

        public Criteria andBei_tuiIsNull() {
            addCriterion("bei_tui is null");
            return (Criteria) this;
        }

        public Criteria andBei_tuiIsNotNull() {
            addCriterion("bei_tui is not null");
            return (Criteria) this;
        }

        public Criteria andBei_tuiEqualTo(Integer value) {
            addCriterion("bei_tui =", value, "bei_tui");
            return (Criteria) this;
        }

        public Criteria andBei_tuiNotEqualTo(Integer value) {
            addCriterion("bei_tui <>", value, "bei_tui");
            return (Criteria) this;
        }

        public Criteria andBei_tuiGreaterThan(Integer value) {
            addCriterion("bei_tui >", value, "bei_tui");
            return (Criteria) this;
        }

        public Criteria andBei_tuiGreaterThanOrEqualTo(Integer value) {
            addCriterion("bei_tui >=", value, "bei_tui");
            return (Criteria) this;
        }

        public Criteria andBei_tuiLessThan(Integer value) {
            addCriterion("bei_tui <", value, "bei_tui");
            return (Criteria) this;
        }

        public Criteria andBei_tuiLessThanOrEqualTo(Integer value) {
            addCriterion("bei_tui <=", value, "bei_tui");
            return (Criteria) this;
        }

        public Criteria andBei_tuiIn(List<Integer> values) {
            addCriterion("bei_tui in", values, "bei_tui");
            return (Criteria) this;
        }

        public Criteria andBei_tuiNotIn(List<Integer> values) {
            addCriterion("bei_tui not in", values, "bei_tui");
            return (Criteria) this;
        }

        public Criteria andBei_tuiBetween(Integer value1, Integer value2) {
            addCriterion("bei_tui between", value1, value2, "bei_tui");
            return (Criteria) this;
        }

        public Criteria andBei_tuiNotBetween(Integer value1, Integer value2) {
            addCriterion("bei_tui not between", value1, value2, "bei_tui");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table live
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table live
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}