package com.yy.buy.domain;

import java.util.Date;

public class OrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.orderId
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.productId
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.productName
     *
     * @mbggenerated
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.originalPrice
     *
     * @mbggenerated
     */
    private Integer originalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.discountPrice
     *
     * @mbggenerated
     */
    private Integer discountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.totalOriginalPrice
     *
     * @mbggenerated
     */
    private Integer totalOriginalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.totalDiscountPrice
     *
     * @mbggenerated
     */
    private Integer totalDiscountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.snapshotImageList
     *
     * @mbggenerated
     */
    private String snapshotImageList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.buyCount
     *
     * @mbggenerated
     */
    private Integer buyCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.uid
     *
     * @mbggenerated
     */
    private Long uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.orderStatus
     *
     * @mbggenerated
     */
    private Integer orderStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.orderId
     *
     * @return the value of order_detail.orderId
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.orderId
     *
     * @param orderId the value for order_detail.orderId
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.productId
     *
     * @return the value of order_detail.productId
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.productId
     *
     * @param productId the value for order_detail.productId
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.productName
     *
     * @return the value of order_detail.productName
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.productName
     *
     * @param productName the value for order_detail.productName
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.originalPrice
     *
     * @return the value of order_detail.originalPrice
     *
     * @mbggenerated
     */
    public Integer getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.originalPrice
     *
     * @param originalPrice the value for order_detail.originalPrice
     *
     * @mbggenerated
     */
    public void setOriginalPrice(Integer originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.discountPrice
     *
     * @return the value of order_detail.discountPrice
     *
     * @mbggenerated
     */
    public Integer getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.discountPrice
     *
     * @param discountPrice the value for order_detail.discountPrice
     *
     * @mbggenerated
     */
    public void setDiscountPrice(Integer discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.totalOriginalPrice
     *
     * @return the value of order_detail.totalOriginalPrice
     *
     * @mbggenerated
     */
    public Integer getTotalOriginalPrice() {
        return totalOriginalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.totalOriginalPrice
     *
     * @param totalOriginalPrice the value for order_detail.totalOriginalPrice
     *
     * @mbggenerated
     */
    public void setTotalOriginalPrice(Integer totalOriginalPrice) {
        this.totalOriginalPrice = totalOriginalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.totalDiscountPrice
     *
     * @return the value of order_detail.totalDiscountPrice
     *
     * @mbggenerated
     */
    public Integer getTotalDiscountPrice() {
        return totalDiscountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.totalDiscountPrice
     *
     * @param totalDiscountPrice the value for order_detail.totalDiscountPrice
     *
     * @mbggenerated
     */
    public void setTotalDiscountPrice(Integer totalDiscountPrice) {
        this.totalDiscountPrice = totalDiscountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.snapshotImageList
     *
     * @return the value of order_detail.snapshotImageList
     *
     * @mbggenerated
     */
    public String getSnapshotImageList() {
        return snapshotImageList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.snapshotImageList
     *
     * @param snapshotImageList the value for order_detail.snapshotImageList
     *
     * @mbggenerated
     */
    public void setSnapshotImageList(String snapshotImageList) {
        this.snapshotImageList = snapshotImageList == null ? null : snapshotImageList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.buyCount
     *
     * @return the value of order_detail.buyCount
     *
     * @mbggenerated
     */
    public Integer getBuyCount() {
        return buyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.buyCount
     *
     * @param buyCount the value for order_detail.buyCount
     *
     * @mbggenerated
     */
    public void setBuyCount(Integer buyCount) {
        this.buyCount = buyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.createTime
     *
     * @return the value of order_detail.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.createTime
     *
     * @param createTime the value for order_detail.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.uid
     *
     * @return the value of order_detail.uid
     *
     * @mbggenerated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.uid
     *
     * @param uid the value for order_detail.uid
     *
     * @mbggenerated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.orderStatus
     *
     * @return the value of order_detail.orderStatus
     *
     * @mbggenerated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.orderStatus
     *
     * @param orderStatus the value for order_detail.orderStatus
     *
     * @mbggenerated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderDetail other = (OrderDetail) that;
        return (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
            && (this.getOriginalPrice() == null ? other.getOriginalPrice() == null : this.getOriginalPrice().equals(other.getOriginalPrice()))
            && (this.getDiscountPrice() == null ? other.getDiscountPrice() == null : this.getDiscountPrice().equals(other.getDiscountPrice()))
            && (this.getTotalOriginalPrice() == null ? other.getTotalOriginalPrice() == null : this.getTotalOriginalPrice().equals(other.getTotalOriginalPrice()))
            && (this.getTotalDiscountPrice() == null ? other.getTotalDiscountPrice() == null : this.getTotalDiscountPrice().equals(other.getTotalDiscountPrice()))
            && (this.getSnapshotImageList() == null ? other.getSnapshotImageList() == null : this.getSnapshotImageList().equals(other.getSnapshotImageList()))
            && (this.getBuyCount() == null ? other.getBuyCount() == null : this.getBuyCount().equals(other.getBuyCount()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getOrderStatus() == null ? other.getOrderStatus() == null : this.getOrderStatus().equals(other.getOrderStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getOriginalPrice() == null) ? 0 : getOriginalPrice().hashCode());
        result = prime * result + ((getDiscountPrice() == null) ? 0 : getDiscountPrice().hashCode());
        result = prime * result + ((getTotalOriginalPrice() == null) ? 0 : getTotalOriginalPrice().hashCode());
        result = prime * result + ((getTotalDiscountPrice() == null) ? 0 : getTotalDiscountPrice().hashCode());
        result = prime * result + ((getSnapshotImageList() == null) ? 0 : getSnapshotImageList().hashCode());
        result = prime * result + ((getBuyCount() == null) ? 0 : getBuyCount().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getOrderStatus() == null) ? 0 : getOrderStatus().hashCode());
        return result;
    }
}