package com.yy.buy.domain;

public class OrderMapper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mapper.payOrderId
     *
     * @mbggenerated
     */
    private Long payOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mapper.orderId
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mapper.payOrderId
     *
     * @return the value of order_mapper.payOrderId
     *
     * @mbggenerated
     */
    public Long getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mapper.payOrderId
     *
     * @param payOrderId the value for order_mapper.payOrderId
     *
     * @mbggenerated
     */
    public void setPayOrderId(Long payOrderId) {
        this.payOrderId = payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mapper.orderId
     *
     * @return the value of order_mapper.orderId
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mapper.orderId
     *
     * @param orderId the value for order_mapper.orderId
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_mapper
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderMapper other = (OrderMapper) that;
        return (this.getPayOrderId() == null ? other.getPayOrderId() == null : this.getPayOrderId().equals(other.getPayOrderId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_mapper
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPayOrderId() == null) ? 0 : getPayOrderId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        return result;
    }
}